use master
ALTER DATABASE Globalfs SET SINGLE_USER WITH ROLLBACK IMMEDIATE    
ALTER DATABASE Globalfs MODIFY NAME = [Globalfs_1]
ALTER DATABASE Globalfs_1 SET RESTRICTED_USER
--ALTER DATABASE Globalfs_1 SET MULTI_USER