-- Agrega filegroup
ALTER DATABASE [DWH] ADD FILEGROUP FILEGROUP_NAME
ALTER DATABASE [DWH] ADD FILE ( 
NAME = N'DATAFILE_NAME', FILENAME = N'J:\BD\Data\DWH\DATAFILE_NAME.ndf',
SIZE = 100, FILEGROWTH = 256) TO FILEGROUP FILEGROUP_NAME

-- Borra filegroup
ALTER DATABASE [DWH] REMOVE FILE DATAFILE_NAME
ALTER DATABASE [DWH] REMOVE FILEGROUP FILEGROUP_NAME

