SELECT
	C.[NUMBER],
	T.[ASSIGNED_TO],
	C.[REQUESTED_BY],
	C.[PLANNED_START],
	C.[PLANNED_END],
	T.[NUMBER],
	DATENAME(DW,C.[PLANNED_END]) [SUBMIT_DAYS],
	DATEDIFF(DAY,C.[PLANNED_END] - CAST('04:30' AS DATETIME), GETDATE()) [DAYS],
	CONVERT(VARCHAR(10), ((DATEDIFF(MS, C.[PLANNED_END] - CAST('04:30' AS DATETIME), GETDATE())%86400000)/3600000)) + ':'+ -- HOURS
	CONVERT(VARCHAR(10), (((DATEDIFF(MS, C.[PLANNED_END] - CAST('04:30' AS DATETIME), GETDATE())%86400000)%3600000)/60000)) + ':'+ -- MINUTES
	CONVERT(VARCHAR(10), ((((DATEDIFF(MS, C.[PLANNED_END] - CAST('04:30' AS DATETIME), GETDATE())%86400000)%3600000)%60000)/1000)) -- SECONDS
	[TIME],
	T.[DESCRIPTION]
FROM [SMBODSA2].[dbo].[CM3TM1] T
INNER JOIN [SMBODSA2].[dbo].[CM3RM1] C ON C.NUMBER = T.PARENT_CHANGE
WHERE T.[STATUS] = 'initial' 
AND C.[CURRENT_PHASE] IN ('Evaluación & Cierre del Cambio','Implementación del Cambio')
AND T.[ASSIGN_DEPT] = ('ADM BASES DE DATOS DISTRIBUIDA')
AND T.[COMPLETION_CODE] IS NULL
ORDER BY c.[PLANNED_END];